
# file name of the "go run" command
main              : main.go

# 你的项目在本机运行端口
app_port          : "5000-5010"

# go build -o 命令生成的二进制文件保存位置
app_buildDir      :   ""
# 指定app端口的参数名，例如：webx.exe -p 8080 其中的“-p”就是。
app_portParamName : ""

# 你的项目对外公开访问的端口
pxy_port          : 8080

# file types to watch for changes in. use "|" to separate multiple types, for example, go|html
watch             : go

# 默认会自动监控上面main参数所指定的文件所在之文件夹，如果你还要监控其它文件夹，请在这里指定。
# 如要指定多个文件夹路径，请用“|”分隔。
watch_otherDir    : ""
